baseURL = "https://cousigoico.github.io/Portfolio/"
languageCode = "es"
title = "Mi Blog Técnico"
theme = "hugo-theme-dream"
themesDir = "../../themes"

[params]
  author = "Fco. Javier Cousiño"
  avatar = "img/Icono.png"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
